name: build

on: push
  job1 name:
    name: Running the first Job
      runs-on: ubuntu-latest
      steps:
        - name: step one
          uses: actions/checkout@v2
        - name: second step
           run:  env | sort

  job2 name: 
    name: Running the Second Job
    runs-on: windows-latest
    steps: 
      - name: Job 2 step 2
        uses: actions/checkout@v2
      - name: Job 2 step 2
         run: "Get-ChildItem Env: | Sort-Object Name"

